ALTER TABLE characters
    ADD COLUMN size TEXT NOT NULL DEFAULT '',
    ADD COLUMN height TEXT NOT NULL DEFAULT '',
    ADD COLUMN weight TEXT NOT NULL DEFAULT '',
    ADD COLUMN eye_color TEXT NOT NULL DEFAULT '',
    ADD COLUMN hair_color TEXT NOT NULL DEFAULT '',
    ADD COLUMN skin_color TEXT NOT NULL DEFAULT '',
    ADD COLUMN look_description TEXT NOT NULL DEFAULT '';