apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagger-adventure
  namespace: argocd
spec:
  project: default
  source:
    # replace with this repo's actual clone URL
    repoURL: https://github.com/pierrot32/DaggerAdventure
    targetRevision: production
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dagger-adventure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
